# Generated by Django 5.2.7 on 2026-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('EL', 'Earned Leave')], default='CL', max_length=2),
        ),
    ]
